apiVersion: v1
kind: Service
metadata:
  name: vcluster-loadbalancer
  namespace: vcluster-demo-cluster-00002
spec:
  loadBalancerIP: 10.17.12.232
  selector:
    app: vcluster
    release: demo-cluster-2
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
  type: LoadBalancer
