apiVersion: gitops.weave.works/v1alpha1
kind: GitopsCluster
metadata:
  name: hephy-stg
  namespace: capi-secrets
  # Signals that this cluster should be bootstrapped.
  labels:
    weave.works/capi: bootstrap
spec:
  secretRef:
    name: hephy-stg-kubeconfig
