apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: moo
  namespace: vcluster-moo-cluster
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: moo
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: moo
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: moo
  namespace: vcluster-moo-cluster
spec:
  controlPlaneEndpoint:
    host: ""
    port: 0
  helmRelease:
    chart:
      name: vcluster
      repo: https://charts.loft.sh
      version: 0.20.0
    values: |
      controlPlane:
        ingress:
          enabled: true
          host: moo-cluster.turkey.local
          spec:
            tls:
            - hosts:
              - moo-cluster.turkey.local
              secretName: testsecret-tls
        distro:
          k3s:
            enabled: true
            extraArgs:
            - --kube-apiserver-arg=oidc-issuer-url=https://dex.howard.moomboo.space
            - --kube-apiserver-arg=oidc-client-id=wg-kubelogin
            - --kube-apiserver-arg=oidc-groups-claim=groups
            image:
              tag: v1.28.5-k3s1
        proxy:
          extraSANs:
          - moo-cluster.turkey.local
        statefulSet:
          scheduling:
            podManagementPolicy: OrderedReady
      sync:
        fromHost:
          ingressClasses:
            enabled: true
          nodes:
            enabled: true
        toHost:
          ingresses:
            enabled: true
          persistentVolumes:
            enabled: true
          storageClasses:
            enabled: true
