apiVersion: v1
kind: Namespace
metadata:
  name: vcluster-demo-cluster-00002
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: demo-cluster-2
  namespace: vcluster-demo-cluster-00002
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: demo-cluster-2
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: demo-cluster-2
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: demo-cluster-2
  name: demo-cluster-2
  namespace: vcluster-demo-cluster-00002
spec:
  controlPlaneEndpoint:
    host: demo-cluster-2.turkey.local
    port: 443
  kubernetesVersion: 1.23.13
  helmRelease:
    values: |-
      syncer:
        extraArgs:
        - --tls-san=demo-cluster-2.turkey.local
      sync:
        nodes:
          enabled: true
          nodeSelector: "kubernetes.io/hostname=msigaming"
        persistentvolumes:
          enabled: true
        # If you want to create custom storage classes
        # inside the vcluster.
        storageclasses:
          enabled: true
        ingresses:
          enabled: true
