# kind: Namespace
# apiVersion: v1
# metadata:
#   name: vcluster-howard-moomboo-space
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: howard-moomboo-cluster
  namespace: vcluster-howard-moomboo-space
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: howard-moomboo-cluster
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: howard-moomboo-cluster
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: howard-moomboo-cluster
  name: howard-moomboo-cluster
  namespace: vcluster-howard-moomboo-space
spec:
  controlPlaneEndpoint:
    host: howard.moomboo.space
    port: 443
  helmRelease:
    chart:
      name: vcluster
      version: v0.20.0-beta.6
    values: |-
      controlPlane:
        advanced:
          virtualScheduler:
            enabled: true
        distro:
          k3s:
            enabled: true
            extraArgs:
            - --kube-apiserver-arg=oidc-issuer-url=https://dex.howard.moomboo.space
            - --kube-apiserver-arg=oidc-client-id=wg-kubelogin
            - --kube-apiserver-arg=oidc-groups-claim=groups
            image:
              tag: v1.30.1-k3s1
        proxy:
          extraSANs:
          - howard.moomboo.space
        statefulSet:
          scheduling:
            nodeSelector:
              kubernetes.io/hostname: msigaming
            podManagementPolicy: OrderedReady
      sync:
        fromHost:
          ingressClasses:
            enabled: true
          nodes:
            enabled: true
        toHost:
          ingresses:
            enabled: true
          persistentVolumes:
            enabled: true
