# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: vcluster-hephy-stg-turkey-local
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: hephy-stg
  namespace: vcluster-hephy-stg-turkey-local
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: hephy-stg
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: hephy-stg
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: hephy-stg
  name: hephy-stg
  namespace: vcluster-hephy-stg-turkey-local
spec:
  controlPlaneEndpoint:
    host: hephy-stg.turkey.local
    port: 443
  kubernetesVersion: "1.28"
  helmRelease:
    values: |-
      vcluster:
        image: rancher/k3s:v1.28.2-k3s1
        extraArgs:
        - --kube-apiserver-arg --oidc-issuer-url=https://dex.howard.moomboo.space
        - --kube-apiserver-arg --oidc-client-id=wg-kubelogin
        - --kube-apiserver-arg --oidc-groups-claim=groups
      syncer:
        extraArgs:
        - --tls-san=hephy-stg.turkey.local
      sync:
        nodes:
          enabled: true
          nodeSelector: "kubernetes.io/hostname=msigaming"
        persistentvolumes:
          enabled: true
        # If you want to create custom storage classes
        # inside the vcluster.
        storageclasses:
          enabled: false
        ingresses:
          enabled: true
