kind: Namespace
apiVersion: v1
metadata:
  name: vcluster-howard-moomboo-stage
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: howard-moomboo-staging
  namespace: vcluster-howard-moomboo-stage
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: howard-moomboo-staging
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: howard-moomboo-staging
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: howard-moomboo-staging
  name: howard-moomboo-staging
  namespace: vcluster-howard-moomboo-stage
spec:
  controlPlaneEndpoint:
    host: howard.moomboo.stage
    port: 443
  kubernetesVersion: "1.27"
  helmRelease:
    values: |-
      vcluster:
        image: rancher/k3s:v1.27.4-k3s1
        extraArgs:
        - --kube-apiserver-arg --oidc-issuer-url=https://dex.howard.moomboo.space
        - --kube-apiserver-arg --oidc-client-id=wg-kubelogin
        - --kube-apiserver-arg --oidc-groups-claim=groups
      syncer:
        extraArgs:
        - --tls-san=howard.moomboo.stage
      sync:
        nodes:
          enabled: false
          nodeSelector: "kubernetes.io/hostname=hpworker01"
        persistentvolumes:
          enabled: false
        # If you want to create custom storage classes
        # inside the vcluster.
        storageclasses:
          enabled: false
        ingresses:
          enabled: false

